name: Release binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build ./cmd/main.go -o clouflareupdatedns
        env:
          CGO_ENABLED: 0
          GOOS: linux

      - name: Archive binary
        run: |
          tar -czf clouflareupdatedns.tar.gz clouflareupdatedns

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BASEMENT_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: clouflareupdatedns.tar.gz
