name: Publish cloudflarednsupdate

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:

  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io/mario-pz
          username: ${{ github.actor }}
          password: ${{ secrets.BASEMENT_KEY }}
          ecr: auto
          logout: true

      - name: Build cloudflarednsupdate
        run: |
            docker build . -t ghcr.io/mario-pz/${{ github.event.repository.name }}:${GITHUB_REF##*/}

      - name: Push cloudflarednsupdate
        run: |
            docker push ghcr.io/mario-pz/${{ github.event.repository.name }}:${GITHUB_REF##*/}
